brew cask install google-chrome
brew cask install vlc
brew cask install virtualbox
brew cask install android-file-transfer
brew cask install komodo-edit
brew cask install picasa
brew cask install flash
brew cask install eclipse-ide
brew cask install java
brew cask install firefox
brew cask install wunderlist
brew cask install sparrow
brew cask install iterm2
brew cask install skype
brew cask install evernote
brew cask install qq
brew cask install keka
brew cask install quicksilver
brew cask install xunlei
brew cask install electrum
brew cask install wunderlist
brew cask install github
brew cask install sourcetree